name: Simorgh CI - Unit/Integration Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install & build
        run: |
          npm ci
          npm run build
      - name: Unit Tests
        run: |
          npm run test:unit
      - name: Integration Tests
        run: |
          npm run test:integration:ci
      - name: Linting
        run: |
          npm run test:lint
      - name: Puppeteer
        run: |
          npm run test:puppeteer
      - name: BBC A11y
        run: |
          npm run start && npm run bbcA11y

        env:
          CI: true
          LOG_LEVEL: 'error'
